In [29]:
import pickle
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import MiniBatchKMeans, KMeans
from tqdm.auto import tqdm

In [4]:
with open('X_out_train.pickle', 'rb') as f:
    X_train = pickle.load(f)
# with open('Y_out_train.pickle', 'rb') as f:
#     Y_train = pickle.load(f)

In [6]:
k = 10 # сколько кластеров????
model_km = MiniBatchKMeans(n_clusters=k, max_iter=10, batch_size = 3000)
model_km.fit(X_train)

MiniBatchKMeans(batch_size=3000, max_iter=10, n_clusters=1000)

In [9]:
print(model_km.cluster_centers_)

2.5506752731280473


In [30]:
with open('X_out_test.pickle', 'rb') as f:
    X_test = pickle.load(f)
with open('count_sent_in_text_X_test.pickle', 'rb') as f:
    count_sent_X_test = pickle.load(f)
with open('count_sent_in_text_Y_test.pickle', 'rb') as f:
    count_sent_Y_test = pickle.load(f)

In [31]:
index_sent_for_summ = []
new_text_start = 0
for text_ind in tqdm(range(len(count_sent_X_test))):
    text_end = new_text_start + count_sent_X_test[text_ind]
    text = X_test[new_text_start : text_end]
    cluster_count = count_sent_Y_test[text_ind]
    
    model_km = KMeans(n_clusters = cluster_count)
    cluster_field = model_km.fit(text)
#     predict_cluster = model_km.predict(text)
    distance_to_cluster = model_km.transform(text)
    
    sent_ind_close_centroids = np.argmin(distance_to_cluster, axis=0)
    index_sent_for_summ.append(sent_ind_close_centroids)
    new_text_start = text_end
    if text_ind%500==0:
        print(sent_ind_close_centroids, new_text_start)
#     print(sent_ind_close_centroids)
#     print(model_km.cluster_centers_[1][8000:9000])

  0%|          | 0/5770 [00:00<?, ?it/s]

[ 3 14] 25
[33  6  4 15] 19101
[19  6  3] 38022
[23 36  5] 56568
[17  7 16] 75597
[39 28 34 11] 94343
[ 9  1 17] 112855
[ 0 22  5] 131907
[14 28 29 24] 150613
[15 25 27] 169600
[7 9] 188696
[9] 207704


In [34]:
with open('cluster_index_sent_for_summ_X_test.pickle', 'wb') as f:
    pickle.dump(np.array(index_sent_for_summ), f)

<ipython-input-34-2ddc1f4f4d70>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  pickle.dump(np.array(index_sent_for_summ), f)
